### ISSUE TITLE
This package need to be updated for Flutter 3.0

### ISSUE THREAD

**Issue by md-siam** [aeyrium/cube_transition#12]
I am getting this warning in Flutter 3.0
![Screen Shot 2022-05-28 at 11 50 48 AM](https://user-images.githubusercontent.com/21225918/170812171-8c565e77-5306-46d9-b350-d08874281636.png)

Please upgrade this package. 
Thanks for this awesome package. 👍

**Comment by vladyslav-ulianytskyi** [comment]
looks like this repo does not supported

**Comment by md-siam** [comment]
This package needs simple upgrading.
